export const insuranceProvider = [
    "1st Agency",
    "20/20 Eyecare Plan",
    "AARP",
    "Absolute Total Care",
    "Access Medicare (NY)",
    "Accountable Health Plan of Ohio",
    "ACE",
    "AdvantageMD",
    "Advantica",
    "Advent Health",
    "Adventist Health",
    "Advocate Health Care",
    "Aetna",
    "Aetna Better Health",
    "Affinity Health Plan",
    "AgeWell New York",
    "Agile Health Insurance",
    "AIG",
    "Alameda Alliance for Health",
    "Alignment Health Plan",
    "All Savers Insurance",
    "AllCare Health",
    "Allegiance Life and Health",
    "Alliant Health Plans",
    "Allianz Worldwide Care",
    "AllWays Health Partners",
    "Allwell",
    "AlohaCare",
    "AlphaCare",
    "AltaMed Senior BuenaCare (PACE)",
    "Altius (Coventry Health Care)",
    "AlwaysCare",
    "Ambetter",
    "American Behavioral",
    "American Eldercare",
    "American Healthcare Alliance",
    "American Maritime Officers Plans",
    "American Republic Insurance Company",
    "America's 1st Choice",
    "AmeriGroup",
    "AmeriHealth",
    "AmeriHealth Caritas",
    "Amida Care",
    "Amish Church Fund",
    "Amplifon Hearing Health Care",
    "Anthem Blue Cross",
    "Anthem Blue Cross Blue Shield",
    "APWU",
    "ArchCare",
    "Arise Health Plan",
    "Arizona Complete Health",
    "Arizona Foundation for Medical Care",
    "Arkansas Blue Cross Blue Shield",
    "Ascension Health",
    "Assurant Employee Benefits",
    "Assurant Health",
    "Asuris Northwest Health",
    "ATRIO Health Plans",
    "Aultcare",
    "Avera Health Plans",
    "Avesis",
    "AVMA Life",
    "AvMed",
    "Banker's Life",
    "Banner Health",
    "Baptist Health Plan",
    "Beacon Health Options",
    "Beaumont Employee Health Plan",
    "Beech Street",
    "Best Choice Plus",
    "Best Doctors Insurance",
    "Best Life And Health",
    "Better Health (Florida Medicaid)",
    "Block Vision",
    "Blue Choice Health Plan",
    "Blue Cross Blue Shield Federal Employee Program",
    "Blue Cross Blue Shield of Alabama",
    "Blue Cross Blue Shield of Arizona",
    "Blue Cross Blue Shield of Georgia",
    "Blue Cross Blue Shield of Illinois",
    "Blue Cross Blue Shield of Kansas",
    "Blue Cross Blue Shield of Kansas City",
    "Blue Cross Blue Shield of Louisiana",
    "Blue Cross Blue Shield of Massachusetts",
    "Blue Cross Blue Shield of Michigan",
    "Blue Cross Blue Shield of Minnesota",
    "Blue Cross Blue Shield of Mississippi",
    "Blue Cross Blue Shield of Montana",
    "Blue Cross Blue Shield of Nebraska",
    "Blue Cross Blue Shield of New Mexico",
    "Blue Cross Blue Shield of North Carolina",
    "Blue Cross Blue Shield of North Dakota",
    "Blue Cross Blue Shield of Oklahoma",
    "Blue Cross Blue Shield of Rhode Island",
    "Blue Cross Blue Shield of South Carolina",
    "Blue Cross Blue Shield of Tennessee",
    "Blue Cross Blue Shield of Texas",
    "Blue Cross Blue Shield of Vermont",
    "Blue Cross Blue Shield of Western New York",
    "Blue Cross Blue Shield of Wyoming",
    "Blue Cross of Idaho",
    "Blue Cross of Northeastern Pennsylvania",
    "Blue Shield of California",
    "Blue Shield of Northeastern New York",
    "BMC HealthNet Plan",
    "Brand New Day",
    "BridgeSpan",
    "Bridgeway Health Solutions",
    "Bright Health",
    "Buckeye Health Plan",
    "California Foundation for Medical Care",
    "California Health and Wellness",
    "CalOptima",
    "CalPERS",
    "CalViva Health",
    "Calvos",
    "Cambridge Health Alliance (CHA)",
    "Canal Insurance Company",
    "Capital Blue Cross",
    "Capital Health Plan",
    "Care Access Health Plan",
    "Care Improvement Plus",
    "Care N' Care",
    "Care1st",
    "CareConnect",
    "CareFirst Blue Cross Blue Shield",
    "CareMore",
    "CareOregon",
    "CarePlus Health Plans (Florida Medicare)",
    "CarePoint Health Plans",
    "CareSource",
    "Cascade Health Alliance",
    "CastlePoint",
    "Caterpillar",
    "CBA Blue",
    "CDPHP",
    "CeltiCare Health Plan",
    "CenCal Health",
    "Cenpatico",
    "Centennial Care",
    "CenterLight Healthcare",
    "Centers for Medicare & Medicaid Services",
    "Centers Plan for Healthy Living",
    "Central California Alliance for Health",
    "Central Health Plan of California",
    "Central Mutual Insurance Company",
    "Century Healthcare - CHC",
    "CHAMPVA",
    "Children's Community Health Plan",
    "Children's Medical Services (CMS)",
    "Chinese Community Health Plan",
    "Choice Care Network",
    "CHP Group",
    "Christian Healthcare Ministries",
    "CHRISTUS Health Plan",
    "CHUBB",
    "Cigna",
    "Cigna-HealthSpring",
    "Citizens United Reciprocal Exchange (CURE)",
    "Clark County Self-Funded Health",
    "Clements Worldwide",
    "Cleveland Clinic Employee Health Plan",
    "Clover Health",
    "Cofinity",
    "Colonial Life",
    "Colorado Access",
    "Columbia United Providers",
    "Common Ground Healthcare Cooperative",
    "Commonwealth Care",
    "Commonwealth Care Alliance",
    "Community Behavioral Health",
    "Community Care Alliance of Illinois",
    "Community Care Associates",
    "Community Care Behavioral Health Organization",
    "Community Care of North Carolina",
    "Community Eye Care",
    "Community First Health Plans",
    "Community Health Choice",
    "Community Health Group",
    "Community Health Options",
    "Community Health Partners",
    "Community Health Plan of Washington",
    "CommunityCare of Oklahoma",
    "Companion Life",
    "CompBenefits",
    "Comprehensive Health Insurance Plan (CHIP) of Illinois",
    "Comprehensive Medical and Dental Program (CMDP)",
    "ComPsych",
    "Connect Care",
    "ConnectiCare",
    "Consolidated Health Plans",
    "Constitution Life",
    "Consumer Health Network",
    "Continental Casualty Company",
    "Contra Costa Health Plan",
    "Cook Children's Health Plan",
    "Coordinated Care Health",
    "Corvel",
    "CountyCare (Cook County)",
    "Coventry Health Care",
    "Cox HealthPlans",
    "Create",
    "Crystal Run Health Plans",
    "Culinary Health Fund",
    "DAKOTACARE",
    "Davis Vision",
    "DC Medicaid",
    "Dean Health Plan",
    "Denver Health Medical Plan",
    "Department of Medical Assistance Services",
    "Deseret Mutual",
    "Devon Health Services",
    "Dimension Health",
    "DMC Care",
    "DOCS (Doctors of the Oregon South Coast)",
    "Driscoll Health Plan",
    "Easy Choice Health Plan (California)",
    "Easy Choice Health Plan of New York",
    "EHP Significa",
    "El Paso First Health Plans",
    "Elderplan",
    "EmblemHealth",
    "EmblemHealth (formerly known as GHI)",
    "EmblemHealth (formerly known as HIP)",
    "EMI Health",
    "Empire Blue Cross Blue Shield",
    "Empire BlueCross BlueShield HealthPlus",
    "Empire Plan",
    "Encore Health Network",
    "Envolve Benefit Options",
    "Eon Health",
    "Epic Hearing Health Care",
    "Erickson Advantage",
    "ESSENCE Healthcare",
    "Esurance",
    "EverCare",
    "Evergreen Health Cooperative",
    "Evolutions Healthcare Systems",
    "Excellus Blue Cross Blue Shield",
    "Extended Managed Long Term Care",
    "EyeMed",
    "Eyetopia Vision Care",
    "Fallon Community Health Plan (FCHP)",
    "Family Health Network",
    "FamilyCare Health Plans",
    "Fidelis Care (NY)",
    "Fidelity",
    "First Choice Health",
    "First Choice Health Plan of Mississippi",
    "First Health (Coventry Health Care)",
    "FirstCare Health Plans",
    "FirstCarolinaCare",
    "Florida Blue: Blue Cross Blue Shield of Florida",
    "Florida Health Care Plans",
    "Florida Health Partners",
    "Florida Hospital Healthcare System (FHHS)",
    "Florida KidCare",
    "Fort Bend County Indigent Health Care",
    "Fortified Provider Network",
    "Freedom Health",
    "Fresenius Health Plans",
    "Friday Health Plans",
    "Galaxy Health",
    "Gateway Health",
    "GEHA",
    "Geisinger Health Plan",
    "GEMCare Health Plan",
    "General Vision Services (GVS)",
    "GeoBlue",
    "Gilsbar 360 Alliance",
    "Global Health",
    "Gold Coast Health Plan",
    "Golden Rule",
    "Golden State Medicare Health Plan",
    "Great American Insurance",
    "Group Health Cooperative",
    "Group Health Cooperative of Eau Claire",
    "Group Health Cooperative of South Central Wisconsin",
    "Guardian",
    "Gundersen Health Plan",
    "GWH-Cigna (formerly Great West Healthcare)",
    "Hanover Insurance",
    "HAP (Health Alliance Plan)",
    "HAP Midwest Health Plan",
    "Harken Health",
    "Harmony Health Plan",
    "Harvard Pilgrim Health Care",
    "Hawaii Medical Assurance Association (HMAA)",
    "Hawaii Medical Service Association (HMSA)",
    "Health Alliance",
    "Health Choice",
    "Health Choice Utah",
    "Health First (FL)",
    "Health First Colorado",
    "Health First Health Plans (Florida)",
    "Health Net",
    "Health New England",
    "Health Partners Plans (Pennsylvania)",
    "Health Plan of Nevada",
    "Health Plan of San Joaquin",
    "Health Plan of San Mateo",
    "Health Plus",
    "Health Sun",
    "Healthcare Highways Health Plan",
    "HealthChoice Oklahoma",
    "HealthFirst (NY)",
    "Healthlink",
    "HealthNow",
    "HealthPartners",
    "HealthPlus of Michigan",
    "HealthScope Benefits",
    "HealthSmart",
    "HealthyCT",
    "Hear In America",
    "Heritage Vision Plans",
    "HFN",
    "HFS Medical Benefits",
    "Highmark Blue Cross Blue Shield",
    "Highmark Blue Cross Blue Shield of Delaware",
    "Highmark Blue Shield",
    "Highmark BlueCross BlueShield of West Virginia",
    "Hillsborough Health Care Plan",
    "Home State Health Plan",
    "Hometown Health",
    "Horizon Blue Cross Blue Shield of New Jersey",
    "Horizon Blue Cross Blue Shield of New Jersey For Barbanas Health",
    "Horizon Blue Cross Blue Shield of New Jersey For Novartis",
    "Horizon NJ Health",
    "Hudson Health Plan",
    "Humana",
    "Humana Behavioral Health (LifeSynch)",
    "HUSKY Health",
    "IHC Health Solutions",
    "Illinicare Health",
    "Illinois' Primary Care Case Management (PCCM)",
    "Imagine Health",
    "Imperial Health Plan of California",
    "IMS (Independent Medical Systems)",
    "Independence Blue Cross",
    "Independence Care System",
    "Independent Health",
    "Indiana Medicaid",
    "Ingham Health Plan",
    "Inland Empire Health Plan",
    "Innovation Health",
    "Integra",
    "Inter Valley Health Plan",
    "Intergroup Services",
    "INTotal Health",
    "Iowa MediPASS",
    "Itasca Medical Care",
    "IU Health Plans (Indiana University Health)",
    "Jackson Health Plan",
    "Johns Hopkins Employer Health Programs",
    "Kaiser Permanente",
    "Kansas HealthWave",
    "Kansas Superior Select",
    "KelseyCare Advantage",
    "Keystone First",
    "KPS Health Plans",
    "L.A. Care Health Plan",
    "L.A. Care Health Plan",
    "Land of Lincoln Health",
    "Landmark Healthplan",
    "Legacy Health",
    "Lehigh Valley Health Network Health Plan",
    "Leon Medical Centers Health Plans",
    "Liberty Health Advantage",
    "Liberty Mutual",
    "LifeWise",
    "Lighthouse Guild",
    "Lincoln Financial Group",
    "Louisiana Healthcare Connections",
    "Lutheran Preferred",
    "Magellan Health",
    "MagnaCare",
    "Magnolia Health Plan",
    "Mail Handlers Benefit Plan",
    "MaineCare",
    "Managed Health Network (MHN)",
    "Managed Health Services (Indiana)",
    "Managed Health Services (Wisconsin)",
    "Managed HealthCare Northwest",
    "March Vision Care",
    "Maricopa Health Plan",
    "Martin's Point HealthCare",
    "Maryland Medical Assistance (Medicaid)",
    "Maryland Physicians Care",
    "Massachusetts Laborers' Health & Welfare Fund",
    "MassHealth",
    "Mayo Medical Plan",
    "McLaren Health Plan",
    "MCM Maxcare",
    "MDwise",
    "Medica",
    "Medica HealthCare Plans (Florida)",
    "Medicaid",
    "Medi-Cal",
    "Medical Eye Services (MES Vision)",
    "Medical Mutual",
    "Medicare",
    "MediGold",
    "MediPass",
    "MedStar Family Choice",
    "MedStar Medicare Choice",
    "MedStar Select",
    "Memorial Hermann",
    "Mercy Care",
    "Meridian Health Plan",
    "Meritain Health",
    "MetLife",
    "MetroHealth",
    "MetroPlus Health Plan",
    "Metropolitan Health Plan",
    "MHNet Behavioral Health",
    "Michigan Complete Health",
    "Minuteman Health",
    "Mississippi Division of Medicaid",
    "Missouri Care",
    "MO HealthNet",
    "MOAA (Miltary Officers Association of America)",
    "Moda Health",
    "Molina Healthcare",
    "Montana Health Cooperative",
    "Mountain Health Co-Op",
    "Multiplan PHCS",
    "Mutual of Omaha",
    "MVP Health Care",
    "NALC Health Benefit Plan",
    "National Congress of Employers (NCE)",
    "National Vision Administrators",
    "Nationwide",
    "Navajo Nation",
    "Neighborhood Health Plan (Massachusetts)",
    "Neighborhood Health Plan of Rhode Island",
    "Network Health Plan",
    "Nevada Preferred",
    "New Directions Behavioral Health",
    "New Hampshire Healthy Families",
    "New Mexico Health Connections",
    "New York Hotel Trades Council",
    "NextLevelHealth",
    "Nippon Life Benefits",
    "North Carolina Health Choice (NCHC) for Children",
    "North Shore LIJ CareConnect",
    "NovaNet",
    "NY State No-Fault",
    "Ohara, LLC",
    "Ohio Health Choice",
    "OHMS (Oregon Health Management Services)",
    "On Lok Lifeways",
    "OneNet PPO",
    "Opticare of Utah",
    "OptimaHealth",
    "Optimum HealthCare",
    "Optum Health",
    "Oscar Health Insurance Co.",
    "OSU Health Plan",
    "Oxford (UnitedHealthcare)",
    "PA Medical Assistance",
    "Pacific Health Alliance",
    "PacificSource Health Plans",
    "Palmetto GBA",
    "Pan-American Life Insurance Group",
    "Paramount Healthcare",
    "Parkland Community Health Plan",
    "Parkview Total Health",
    "Partners Health Plan",
    "Partnership HealthPlan of California",
    "Passport Health Plan (Kentucky)",
    "Passport To Health (Montana Medicaid)",
    "Patient 1st (Alabama Medicaid)",
    "PBA (Patrolmen's Benefit Association)",
    "Peach State Health Plan",
    "PeachCare for Kids",
    "PennCare",
    "Peoples Health",
    "Phoenix Health Plan",
    "Physician Assured Access System",
    "Physician Benefits Trust",
    "Physicians Health Plan",
    "Physicians Health Plan of Northern Indiana, Inc.",
    "Physicians Plus Insurance Corporation",
    "PhysiciansCare",
    "Piedmont Community Health Plan",
    "Piedmont WellStar Health Plans",
    "POMCO",
    "Positive Health Care",
    "Preferential Care Network",
    "Preferred Care Partners",
    "PreferredOne",
    "Premera Blue Cross",
    "Premier Health Plan",
    "Presbyterian Health Plan/Presbyterian Insurance Company",
    "Prestige Health Choice",
    "Primary Care Case Management (North Dakota Medicaid)",
    "Prime Health Services, Inc",
    "PrimeWest Health",
    "Principal Financial Group",
    "Priority Health",
    "Priority Partners",
    "Progressive",
    "Prominence Health Plan",
    "Providence Health Plans",
    "ProviDRs Care (WPPA)",
    "Public Aid (Illinois Medicaid)",
    "Public Employees Health Program (PEHP)",
    "QualCare",
    "QualChoice Arkansas",
    "Quality Health Plans of New York",
    "Regence Blue Cross Blue Shield",
    "Regent Insurance",
    "Republic-Franklin Insurance",
    "RiverLink Health",
    "Riverside Health",
    "RiverSpring Health",
    "RLI Indemnity Company",
    "Rocky Mountain Health Plans",
    "Sagamore Health Network",
    "Samaritan Health Plan Operations",
    "SAMBA",
    "San Francisco Health Plan",
    "Sanford Health Plan",
    "Santa Clara Family Health Plan",
    "SCAN Health Plan",
    "Scott & White Health Plan",
    "Security Health Plan of Wisconsin, Inc.",
    "Select Care",
    "Select Health Network",
    "SelectHealth",
    "Sendero Health Plans",
    "Seneca Insurance",
    "Senior Dimensions",
    "Senior Whole Health",
    "Sentry Insurance",
    "Seton Health Plan",
    "Sharp Health Plan",
    "Sierra Health and Life",
    "SightCare",
    "SIHO Insurance Services",
    "SIMNSA Health Plan",
    "Simply Healthcare",
    "Simpra Advantage",
    "Solstice",
    "SoonerCare (Oklahoma Medicaid)",
    "Soundpath Health",
    "South Country Health Alliance",
    "South Florida Community Care Network",
    "Spectera",
    "SSM Health Care",
    "Standard Life and Accident Insurance Company",
    "Stanford Health Care Advantage",
    "StarNet Insurance",
    "State Farm®",
    "State National Insurance",
    "Staywell Insurance",
    "Steward Health Care Network - Health Choice Arizona",
    "Stratose",
    "SummaCare",
    "Sunflower Health Plan",
    "Sunshine Health",
    "Superior HealthPlan",
    "Superior Vision",
    "Sussex Insurance",
    "Sutter Health Plus",
    "SutterSelect",
    "TakeCare",
    "Teachers Health Trust",
    "TexanPlus",
    "Texas Children's Health Plan",
    "Texas Health Aetna",
    "Texas Kids First",
    "Texas Women's Health Program",
    "The Hartford",
    "The Health Plan of the Upper Ohio Valley, Inc.",
    "The HSC Health Care System",
    "TNUS Insurance",
    "Total Health Care",
    "Touchstone",
    "Travelers",
    "Tricare",
    "Trillium Community Health Plan",
    "Trilogy Health Insurance",
    "Triple-S Salud: Blue Cross Blue Shield of Puerto Rico",
    "TrueHealth New Mexico",
    "Trusted Health Plan",
    "Tuality Health Alliance",
    "Tufts Health Freedom Plan",
    "Tufts Health Plan",
    "UCare",
    "UCHP (University of Chicago Health Plan)",
    "UHA Health Insurance",
    "ULLICO Casualty Company",
    "Ultimate Health Plans",
    "UniCare",
    "Uniform Medical Plan",
    "Union Eye Care",
    "Union Health Services, Inc",
    "Union Plans",
    "United American",
    "United Behavioral Health",
    "UnitedHealthcare",
    "UnitedHealthcare Community Plan",
    "UnitedHealthcare Oxford",
    "UnitedHealthOne",
    "Unity Health Insurance",
    "Univera Healthcare",
    "Universal American",
    "Universal Underwriters Insurance",
    "University Hospitals (Health Design Plus)",
    "University of Arizona Health Plans",
    "University of Maryland Health Advantage",
    "University of Utah Health Plans",
    "University Physician Network (UPN)",
    "UPMC Health Plan",
    "US Family Health Plan",
    "US Health Group",
    "USA Managed Care Organization",
    "USAble Mutual Insurance Company",
    "Valley Forge Insurance",
    "Valley Health Plan",
    "Vantage Health Plan, Inc.",
    "Ventura County Health Care Plan",
    "Vibra Health Plan",
    "VillageCareMax",
    "Virginia Coordinated Care (VCC)",
    "Virginia Health Network",
    "Virginia Premier Health Plan",
    "Vision Benefits of America",
    "Vision Care Direct",
    "Vision Plan of America",
    "Viva Health Plan",
    "VNS Choice Health Plans",
    "Volusia Health Network",
    "VSP",
    "Vytra",
    "WEA Trust",
    "Well Sense Health Plan",
    "Wellcare",
    "Wellmark Blue Cross Blue Shield",
    "West American Insurance",
    "West Virginia Senior Advantage",
    "Western Health Advantage",
    "Workers' Compensation",
    "WPS Health Plan",
    "WRM America Indemnity Company",
    "YourCare Health Plan",
    "Zenith"
]