export const speciality = [
   "Acupuncturist",
   "Electrophysiologist",
   "Allergist",
   "Anesthesiologist",
   "Audiologist",
   "Bariatric Physician",
   "Cardiac Electrophysiologist",
   "Cardiologist",
   "Cardiothoracic Surgeon",
   "Chiropractor",
   "Colorectal Surgeon",
   "Dentist",
   "Dermatologist",
   "Dietitian",
   "Ear, Nose &amp; Throat Doctor",
   "Emergency Medicine Physician",
   "Endocrinologist",
   "Endodontist",
   "Family Physician",
   "Gastroenterologist",
   "Geneticist",
   "Geriatrician",
   "Hand Surgeon",
   "Hematologist",
   "Immunologist",
   "Infectious Disease Specialist",
   "Integrative Health Medicine Specialist",
   "Internist",
   "Medical Ethicist",
   "Microbiologist",
   "Midwife",
   "Naturopathic Doctor",
   "Nephrologist",
   "Neurologist",
   "Neuropsychiatrist",
   "Neurosurgeon",
   "Nurse Practitioner",
   "Nutritionist",
   "OB-GYN",
   "Occupational Medicine Specialist",
   "Oncologist",
   "Ophthalmologist",
   "Optometrist",
   "Oral Surgeon",
   "Orthodontist",
   "Orthopedic Surgeon",
   "Pain Management Specialist",
   "Pathologist",
   "Pediatric Dentist",
   "Pediatrician",
   "Periodontist",
   "Physiatrist",
   "Physical Therapist",
   "Physician Assistant",
   "Plastic Surgeon",
   "Podiatrist",
   "Preventive Medicine Specialist",
   "Primary Care Doctor",
   "Prosthodontist",
   "Psychiatrist",
   "Psychologist",
   "Psychosomatic Medicine Specialist",
   "Psychotherapist",
   "Pulmonologist",
   "Radiation Oncologist",
   "Radiologist",
   "Reproductive Endocrinologist",
   "Rheumatologist",
   "Sleep Medicine Specialist",
   "Sports Medicine Specialist",
   "Surgeon",
   "Surgical Oncologist",
   "Travel Medicine Specialist",
   "Urgent Care Specialist",
   "Urological Surgeon",
   "Urologist",
   "Vascular Surgeon"
];